# Generated by Django 4.0.4 on 2022-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='tipo_refeicao',
            field=models.CharField(choices=[('AL', 'Almoço'), ('JA', 'Jantar')], default='AL', max_length=2),
        ),
    ]
